add 112. Path Sum
okuda-seminar/review_leetcode pull request #10
Opened 2021-05-11 14:31 UTC by tkkawa

Please check my code.

2021-05-12 09:53 UTC, ryuji0123 requested changes

2021-05-12 09:53 UTC, ryuji0123 commented on 112_path-sum.py
> +            cur_root, targetSum_rest = stack.pop()
cur_root -> cur_node

2021-05-16 02:52 UTC, tkkawa commented
I modified the code.

2021-06-06 11:00 UTC, ryuji0123 requested changes
check cur_node only

2021-06-27 08:31 UTC, tkkawa commented
I used the recursive function.
Please check my code.

2021-07-06 06:31 UTC, kobakobashu requested changes

2021-07-06 06:31 UTC, kobakobashu commented on 112_path-sum.py
> +            return True
```
if not root.left and not root.right:
    return root.val == targetSum
```
I think this is better.

2021-07-06 06:35 UTC, kobakobashu commented on 112_path-sum.py
> +                or self.hasPathSum(root.right, targetSum - root.val)
unnecessary else, I think.

2021-07-08 07:08 UTC, tkkawa commented
I modified the code.
Please check my code.

2021-07-08 08:30 UTC, kobakobashu approved these changes
LGTM

2023-02-22 08:40 UTC, closed without merging