add 283. Move Zeroes
okuda-seminar/review_leetcode pull request #114
Opened 2021-05-26 15:00 UTC by kobakobashu

time : 15m
Please check my code.

2021-05-29 08:30 UTC, ryuji0123 requested changes
solve this with O(len(nums))

2021-05-29 08:30 UTC, ryuji0123 commented on 283_move-zeroes.py
> +                nums.remove(nums[i])
O(len(nums))

2021-06-22 15:31 UTC, kobakobashu commented
I solved this with O(len(nums)).  Please check my code.

2021-06-23 10:51 UTC, tkkawa approved these changes
LGTM

2023-02-22 08:43 UTC, closed without merging