add 3. Longest Substring Without Repeating Characters
okuda-seminar/review_leetcode pull request #116
Opened 2021-05-27 10:25 UTC by kobakobashu

time : 35m
Please check my code.

2021-05-29 08:28 UTC, ryuji0123 requested changes

2021-05-29 08:28 UTC, ryuji0123 commented on 3_longest-substring-without-repeating-characters.py
> +                sums = ref[alph] + 1
sums is unclear

2021-06-23 07:47 UTC, kobakobashu commented
I changed the unclear name "sums", and fixed the time complexity.  Please check my code.

2021-06-23 07:54 UTC, kobakobashu commented
I fixed the time complexity again.  Please check my code.

2021-06-23 10:58 UTC, tkkawa approved these changes
LGTM

2023-02-22 08:37 UTC, closed without merging