add 290. Word Pattern
okuda-seminar/review_leetcode pull request #120
Opened 2021-05-28 14:52 UTC by kobakobashu

time : 20m
Please check my code.

2021-05-29 08:21 UTC, ryuji0123 requested changes
solve this with O(len(pattern))

2021-05-29 08:21 UTC, ryuji0123 commented on 290_word-pattern.py
> +            elif word in ref.values():
O(len(ref))

2021-06-23 08:03 UTC, kobakobashu commented
I solved this with O(len(pattern)).  Please check my code.

2021-06-24 13:59 UTC, tkkawa approved these changes
LGTM

2023-02-22 08:32 UTC, closed without merging