add 1630. Arithmetic Subarrays
okuda-seminar/review_leetcode pull request #138
Opened 2021-06-01 12:15 UTC by tkkawa

Please check my code.

2021-06-06 10:46 UTC, ryuji0123 requested changes

2021-06-06 10:46 UTC, ryuji0123 commented on 1630_arithmetic-subarrays.py
> +            subarray = sorted(nums[l[i]:r[i] + 1])
subarray = sorted(nums[l[i]: r[i] + 1])

2021-06-08 01:53 UTC, tkkawa commented
I modified the code.
Please check my code.

2021-07-06 07:23 UTC, kobakobashu approved these changes
LGTM

2023-02-22 08:34 UTC, closed without merging