add 1561. Maximum Number of Coins You Can Get
okuda-seminar/review_leetcode pull request #140
Opened 2021-06-02 10:27 UTC by tkkawa

Please check my code.

2021-06-06 10:42 UTC, ryuji0123 requested changes

2021-06-06 10:42 UTC, ryuji0123 commented on 1561_maximum-number-of-coins-you-can-get.py
> +        return sum(sorted(piles)[len(piles)//3 : len(piles) : 2])
sum(sorted(piles)[len(piles)//3: len(piles): 2])

2021-06-08 01:56 UTC, tkkawa commented
I modified the code.
Please check my code.

2021-07-06 07:28 UTC, kobakobashu approved these changes
LGTM

2023-02-22 08:40 UTC, closed without merging