add 383. Ransom Note
okuda-seminar/review_leetcode pull request #154
Opened 2021-06-05 16:26 UTC by kobakobashu

time : 15m
I'm sorry for the late submission. Could you check my code ?

2021-06-06 10:41 UTC, ryuji0123 requested changes

2021-06-06 10:41 UTC, ryuji0123 commented on 383_ransom-note.py
> +        ransomNote_dict = collections.Counter(ransomNote)
ransomNote_counter

2021-06-23 08:30 UTC, kobakobashu commented
I corrected unsuitable names.  Please check my code.

2021-06-28 10:07 UTC, tkkawa approved these changes
LGTM

2021-06-29 10:48 UTC, tkkawa requested changes

2021-06-29 10:48 UTC, tkkawa commented on 383_ransom-note.py
> +import collections
from collections import Counter

2021-06-30 21:43 UTC, kobakobashu commented
I modified my code. Please check it.

2021-07-05 09:45 UTC, tkkawa approved these changes
LGTM

2023-02-22 08:40 UTC, closed without merging