add 387. First Unique Character in a String
okuda-seminar/review_leetcode pull request #156
Opened 2021-06-06 01:58 UTC by kobakobashu

time : 5m
Please check my code.

2021-06-06 10:40 UTC, ryuji0123 requested changes

2021-06-06 10:40 UTC, ryuji0123 commented on 387_first-unique-character-in-a-string.py
> +        s_dict = collections.Counter(s)
s_dict is unclear in this problem

2021-06-25 12:03 UTC, kobakobashu commented
I rename the unclear name "s_dict".  Please check my code.

2021-06-28 10:26 UTC, tkkawa requested changes

2021-06-28 10:26 UTC, tkkawa commented on 387_first-unique-character-in-a-string.py
> +        space: O(1)
space: O(n)

2021-06-30 21:47 UTC, kobakobashu commented
I fixed space complexity.  Please check my code.

2021-07-01 10:35 UTC, tkkawa approved these changes
LGTM

2023-02-22 08:34 UTC, closed without merging