add 448. Find All Numbers Disappeared in an Array
okuda-seminar/review_leetcode pull request #172
Opened 2021-06-10 09:38 UTC by kobakobashu

time : 15m
Please check my code.

2021-06-13 04:44 UTC, ryuji0123 requested changes

2021-06-13 04:44 UTC, ryuji0123 commented on 448_find-all-numbers-disappeared-in-an-array.py
> +        nums_counter = collections.Counter(nums)
```py
from collections import Counter
nums_counter = Counter(nums)
```

2021-06-22 09:13 UTC, kobakobashu commented
I modified my code.  Please check it.

2021-06-29 10:50 UTC, tkkawa approved these changes
LGTM

2023-02-22 08:39 UTC, closed without merging