add 1448. Count Good Nodes in Binary Tree
okuda-seminar/review_leetcode pull request #174
Opened 2021-06-10 09:50 UTC by tkkawa

Please check my code.

2021-06-13 04:43 UTC, ryuji0123 requested changes

2021-06-13 04:43 UTC, ryuji0123 commented on 1448_count-good-nodes-in-binary-tree.py
> +        stack = collections.deque([[root, root.val]])
Completely meaningless lines.
```py
from collections import deque
stack = collections.deque([[root, root.val]])
```

2021-07-03 01:31 UTC, tkkawa commented
I modified the code.
Please check my code.

2021-07-08 15:38 UTC, kobakobashu approved these changes
LGTM

2023-02-22 08:36 UTC, closed without merging