add 1529. Bulb Switcher IV
okuda-seminar/review_leetcode pull request #178
Opened 2021-06-11 10:55 UTC by tkkawa

Please check my code.

2021-06-13 04:41 UTC, ryuji0123 requested changes

2021-06-13 04:41 UTC, ryuji0123 commented on 1529_bulb-switcher-iv.py
> +            if target[i-1] != target[i]: flip_count += 1
```py
if target[i-1] != target[i]: 
    flip_count += 1
```

2021-06-13 12:28 UTC, tkkawa commented
I modified the code.
Please check my code.

2021-06-22 15:14 UTC, kobakobashu approved these changes
LGTM

2023-02-22 08:33 UTC, closed without merging