add 15. 3Sum
okuda-seminar/review_leetcode pull request #186
Opened 2021-06-14 15:24 UTC by kobakobashu

time : 20m
I'm sorry for the late submission. Could you check my code ?

2021-06-21 08:26 UTC, tkkawa requested changes

2021-06-21 08:26 UTC, tkkawa commented on 15_3-sum.py
> +                    if len(output_3_nums) > 0 and cur_3_nums == output_3_nums[-1]:
-> if output_3_nums and cur_3_nums == output_3_nums[-1]:

2021-06-25 12:37 UTC, kobakobashu commented
I modified my code.  Please check my code.

2021-07-02 10:15 UTC, tkkawa approved these changes
LGTM

2023-02-22 08:38 UTC, closed without merging