add 374. Guess Number Higher or Lower
okuda-seminar/review_leetcode pull request #2
Opened 2021-05-11 14:06 UTC by tkkawa

Please check my code.

2021-05-12 09:49 UTC, ryuji0123 requested changes
```py
class Solution:
    def guessNumber(self, n: int) -> int:
        left = 1
        right = n + 1
        
        while left < right:
            mid = left + right >> 1
            comp = guess(mid)
            
            if comp == 0:
                return mid
            
            if 0 < comp:
                left = mid + 1
            else:
                right = mid
                
        return right - 1
```

2021-05-16 01:48 UTC, tkkawa commented
I modified the code.

2021-06-06 10:59 UTC, ryuji0123 requested changes
modify this

2021-06-08 02:02 UTC, tkkawa commented
I modified the code.
Please check my code.

2021-06-13 04:52 UTC, ryuji0123 approved these changes

2021-06-13 04:53 UTC, ryuji0123 requested changes

2021-06-13 04:53 UTC, ryuji0123 commented on 374_guess-number-higher-or-lower.py
> +        return right - 1
return left

2021-06-13 13:01 UTC, tkkawa commented
I modified the code.
Please check my code.

2021-07-02 06:27 UTC, kobakobashu approved these changes
LGTM

2023-02-22 08:45 UTC, closed without merging