add 111. Minimum Depth of Binary Tree
okuda-seminar/review_leetcode pull request #20
Opened 2021-05-11 14:51 UTC by tkkawa

Please check my code.

2021-05-12 10:06 UTC, ryuji0123 requested changes

2021-05-12 10:06 UTC, ryuji0123 commented on 111_minimum-depth-of-binary-tree.py
> +            if cur_root.left:
Stop this. Just check cur_root

2021-05-12 10:06 UTC, ryuji0123 commented on 111_minimum-depth-of-binary-tree.py
> +            if cur_root.left:
I said this before

2021-05-16 03:08 UTC, tkkawa commented
I modified the code.

2021-06-06 11:03 UTC, ryuji0123 requested changes
use either queue and recursive function

2021-07-03 01:04 UTC, tkkawa commented
I modified the code.
Please check my code.

2021-07-06 06:43 UTC, kobakobashu approved these changes
LGTM

2023-02-22 08:37 UTC, closed without merging