add 219. Contains Duplicate II
okuda-seminar/review_leetcode pull request #22
Opened 2021-05-11 14:55 UTC by tkkawa

Please check my code.

2021-05-12 10:05 UTC, ryuji0123 requested changes

2021-05-12 10:05 UTC, ryuji0123 commented on 219_contains-duplicate-ii.py
> +        nums_dict = {}
unclear name

2021-05-12 10:05 UTC, ryuji0123 commented on 219_contains-duplicate-ii.py
> +            if i - nums_dict.get(num, -float('inf')) <= k:
In this case, use float('inf') is unclear.
if num in $(dict_name) and i - $(dict_name)[num] <= k:

2021-07-02 06:48 UTC, kobakobashu approved these changes
LGTM

2023-02-22 08:37 UTC, closed without merging