add 168. Excel Sheet Column Title
okuda-seminar/review_leetcode pull request #50
Opened 2021-05-12 10:17 UTC by kobakobashu

time : 20m
Please check my code.

2021-05-17 13:40 UTC, ryuji0123 requested changes
Empty file.

2021-05-20 08:49 UTC, kobakobashu commented
I fixed empty file.  Please check it.

2021-06-06 11:05 UTC, ryuji0123 requested changes

2021-06-06 11:05 UTC, ryuji0123 commented on 168_excel-sheet-column-title.py
> +        while 26 < cur_quotient:
avoid magic number: 26

2021-06-18 13:32 UTC, kobakobashu commented
I avoided magic number: 26.  Please check my code.

2021-06-22 11:59 UTC, tkkawa approved these changes
LGTM

2023-02-22 08:43 UTC, closed without merging