add 1668. Maximum Repeating Substring
okuda-seminar/review_leetcode pull request #54
Opened 2021-05-12 13:57 UTC by tkkawa

Please check my code.
I think the time complexity is O (n ^ 2) but is it okay because the upper limit of n is 100?

2021-05-17 13:55 UTC, ryuji0123 requested changes
Solve this using binary search

2021-06-20 13:12 UTC, tkkawa commented
I modified the code.
Please check my code.

2021-07-07 15:24 UTC, kobakobashu requested changes

2021-07-07 15:24 UTC, kobakobashu commented on 1668_maximum-repeating-substring.py
> +            mid = (left + right + 1) >> 1
Because the variable "right" is a non-existent value, this "+ 1" is unnecessary, I think.
https://twitter.com/meguru_comp/status/697008509376835584

2021-07-08 07:13 UTC, tkkawa commented
I modified the code.
Please check my code.

2021-07-08 08:32 UTC, kobakobashu approved these changes
LGTM

2023-02-22 08:43 UTC, closed without merging