add 171. Excel Sheet Column Number
okuda-seminar/review_leetcode pull request #56
Opened 2021-05-12 15:00 UTC by kobakobashu

time : 15m
Please check my code.

2021-05-18 10:25 UTC, ryuji0123 requested changes

2021-05-18 10:25 UTC, ryuji0123 commented on 171_excel-sheet-column-number.py
> +        ref = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5, "F": 6, "G": 7, "H": 8, "I": 9, "J": 10, "K": 11, "L": 12, "M": 13, "N": 14, "O": 15, "P": 16, "Q": 17, "R": 18, "S": 19, "T": 20, "U": 21, "V":
use chr and ord functions

2021-05-23 09:18 UTC, kobakobashu commented
I used chr functions.  Please check my code.

2021-06-06 11:05 UTC, ryuji0123 requested changes
avoid magic numbers

2021-06-20 11:05 UTC, kobakobashu commented
I avoided magic number: 26. Please check my code.

2021-06-22 12:03 UTC, tkkawa requested changes

2021-06-22 12:03 UTC, tkkawa commented on 171_excel-sheet-column-number.py
> +        for i in range(1, 27):
-> for i in range(1, num_alp+1):

2021-06-30 21:39 UTC, kobakobashu commented
I modified my code. Please check my code.

2021-07-02 10:22 UTC, tkkawa approved these changes
LGTM

2023-02-22 08:43 UTC, closed without merging