add 434. Number of Segments in a String
okuda-seminar/review_leetcode pull request #63
Opened 2021-05-14 10:47 UTC by tkkawa

Please check my code.

2021-05-17 13:39 UTC, ryuji0123 requested changes

2021-05-17 13:39 UTC, ryuji0123 commented on 434_number-of-segments-in-a-string.py
> +        if not s_strip:
First, check s directly.

2021-05-17 13:39 UTC, ryuji0123 commented on 434_number-of-segments-in-a-string.py
> +        segment_count = 0
Return values in one line with the generator expression.

2021-07-03 00:34 UTC, tkkawa commented
I modified the code.
Please check my code.

2023-02-22 08:33 UTC, closed without merging