add 202. Happy Number
okuda-seminar/review_leetcode pull request #68
Opened 2021-05-15 11:35 UTC by kobakobashu

time : 15m

2021-05-17 13:35 UTC, ryuji0123 requested changes

2021-05-17 13:35 UTC, ryuji0123 commented on 202.happy-number.py
> +        calculate the sum of the squares of its digits.
Check correct docstring styles

2021-05-17 13:35 UTC, ryuji0123 commented on 202.happy-number.py
> +        digit_squares = 0
Use generator and return the value directly

2021-06-01 10:53 UTC, kobakobashu commented
I corrected docstring styles and used generator.  Please check my code.

2021-06-13 04:59 UTC, ryuji0123 reviewed
Why two files are included?

2021-06-13 05:00 UTC, ryuji0123 commented
If you write two solutions, just comment out them except the best one.

2021-06-20 11:16 UTC, kobakobashu commented
I deleted the wrong file.  Please check my code.

2021-07-02 10:32 UTC, tkkawa approved these changes
LGTM

2023-02-22 08:35 UTC, closed without merging