add 204. Count Primes
okuda-seminar/review_leetcode pull request #74
Opened 2021-05-17 06:21 UTC by kobakobashu

time : 30m
Please check my code.

2021-05-17 13:32 UTC, ryuji0123 requested changes

2021-05-17 13:32 UTC, ryuji0123 commented on 204_count-primes.py
> +            if judge_p[num] == 1:
if xx == 0:
    continue

2021-05-17 13:32 UTC, ryuji0123 commented on 204_count-primes.py
> +                for multiple in range(num ** 2, n, num):
multiple is unclear

2021-05-17 13:32 UTC, ryuji0123 commented on 204_count-primes.py
> +        judge_p = [1] * n
Why do you use a list? You can just count prime numbers and its time complexity is the same with current one. Also, judge_p is unclear.

2021-06-20 12:35 UTC, kobakobashu commented on 204_count-primes.py
> +        judge_p = [1] * n
If I don't use a list, its time complexity is same, but time limit exceeded.  So, I used a list.

2023-02-22 08:37 UTC, closed without merging