add 14. Longest Common Prefix
okuda-seminar/review_leetcode pull request #76
Opened 2021-05-17 14:02 UTC by tkkawa

Please check my code.

2021-05-18 10:22 UTC, ryuji0123 requested changes

2021-05-18 10:22 UTC, ryuji0123 commented on 14_longest-common-prefix.py
> +        str_max = max(strs)
unnecessary

2021-05-18 10:22 UTC, ryuji0123 commented on 14_longest-common-prefix.py
> +        for i in range(min(len(str_min), len(str_max))):
Why do you use min(len(str_min), len(str_max))? It's absolutely clear.

2021-07-06 07:10 UTC, kobakobashu approved these changes
LGTM

2023-02-22 08:35 UTC, closed without merging