add 441. Arranging Coins
okuda-seminar/review_leetcode pull request #8
Opened 2021-05-11 14:23 UTC by tkkawa

Please check my code.

2021-05-12 09:52 UTC, ryuji0123 requested changes

2021-05-12 09:52 UTC, ryuji0123 commented on 441_arranging-coins.py
> +        high = n
Set high as invalid value when you use binary search. See this https://twitter.com/meguru_comp/status/697008509376835584

2021-05-16 02:15 UTC, tkkawa commented
I modified the code.

2021-06-06 10:59 UTC, ryuji0123 requested changes
use megru-style

2021-06-08 01:23 UTC, tkkawa commented
I modified the code.
Please check my code.

2021-06-13 04:55 UTC, ryuji0123 requested changes

2021-06-13 04:55 UTC, ryuji0123 commented on 441_arranging-coins.py
> +        res = 0
res is unnecessary

2021-06-13 13:06 UTC, tkkawa commented
I modified the code.
Please check my code.

2021-07-02 06:38 UTC, kobakobashu approved these changes
LGTM

2023-02-22 08:45 UTC, closed without merging